/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  archived?: boolean;
  authorName?: string;
  bookCover?: string;
  isbn?: string;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
