spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: APPLICATION_JSON_VALUE

server:
  servlet:
    context-path: /api/v1
